# Generated by Django 5.0.2 on 2024-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
