# Generated by Django 5.0.2 on 2024-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking_room_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
